/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JFrame;

/**
 *
 * @author Gabriel
 */
public class secretariaMenu extends javax.swing.JFrame {

    private JFrame telaAnterior;
    /**
     * Creates new form secretariaMenu
     */
    public secretariaMenu(JFrame tela) {
        initComponents();
        telaAnterior = tela;
        setLocationRelativeTo(null);
    }

    private secretariaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuText = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        cadastrarPacienteButton = new javax.swing.JButton();
        atualizaPacienteButton = new javax.swing.JButton();
        removePacienteButton = new javax.swing.JButton();
        cadastrarConsultaButton = new javax.swing.JButton();
        atualizaConsultaButton = new javax.swing.JButton();
        removeConsultaButton = new javax.swing.JButton();
        gerarRelatorioConsultaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuText.setText("Menu secretaria");
        menuText.setPreferredSize(new java.awt.Dimension(125, 25));
        getContentPane().add(menuText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        exitButton.setText("Sair");
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 272, -1, -1));

        cadastrarPacienteButton.setText("Cadastrar Paciente");
        cadastrarPacienteButton.setMaximumSize(new java.awt.Dimension(130, 22));
        cadastrarPacienteButton.setPreferredSize(new java.awt.Dimension(130, 22));
        cadastrarPacienteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarPacienteButtonMouseClicked(evt);
            }
        });
        getContentPane().add(cadastrarPacienteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 103, -1, -1));

        atualizaPacienteButton.setText("Atualizar Paciente");
        atualizaPacienteButton.setMaximumSize(new java.awt.Dimension(130, 22));
        atualizaPacienteButton.setPreferredSize(new java.awt.Dimension(130, 22));
        atualizaPacienteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizaPacienteButtonMouseClicked(evt);
            }
        });
        getContentPane().add(atualizaPacienteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 143, -1, -1));

        removePacienteButton.setText("Remover Paciente");
        removePacienteButton.setMaximumSize(new java.awt.Dimension(130, 22));
        removePacienteButton.setPreferredSize(new java.awt.Dimension(130, 22));
        removePacienteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removePacienteButtonMouseClicked(evt);
            }
        });
        getContentPane().add(removePacienteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 183, -1, -1));

        cadastrarConsultaButton.setText("Cadastrar Consulta");
        cadastrarConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarConsultaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarConsultaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 103, -1, -1));

        atualizaConsultaButton.setText("Atualizar Consulta");
        atualizaConsultaButton.setPreferredSize(new java.awt.Dimension(130, 22));
        atualizaConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaConsultaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(atualizaConsultaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 143, -1, -1));

        removeConsultaButton.setText("Remover Consulta");
        removeConsultaButton.setPreferredSize(new java.awt.Dimension(130, 22));
        removeConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeConsultaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(removeConsultaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 183, -1, -1));

        gerarRelatorioConsultaButton.setText("Gerar Relatório de Consulta");
        gerarRelatorioConsultaButton.setMaximumSize(new java.awt.Dimension(170, 22));
        gerarRelatorioConsultaButton.setPreferredSize(new java.awt.Dimension(175, 22));
        gerarRelatorioConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarRelatorioConsultaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(gerarRelatorioConsultaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 223, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        // TODO add your handling code here:
        telaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitButtonMouseClicked

    private void cadastrarPacienteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarPacienteButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        secretariaCadastraPaciente telaCadastro = new secretariaCadastraPaciente(this);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_cadastrarPacienteButtonMouseClicked

    private void removePacienteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removePacienteButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        secretariaRemovePaciente telaRemove = new secretariaRemovePaciente(this);
        telaRemove.setVisible(true);
    }//GEN-LAST:event_removePacienteButtonMouseClicked

    private void atualizaPacienteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizaPacienteButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        secretariaAtualizaPaciente telaAtualiza = new secretariaAtualizaPaciente(this);
        telaAtualiza.setVisible(true);
    }//GEN-LAST:event_atualizaPacienteButtonMouseClicked

    private void cadastrarConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarConsultaButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        secretariaCadastraConsulta tela = new secretariaCadastraConsulta(this);
        tela.setVisible(true);
    }//GEN-LAST:event_cadastrarConsultaButtonActionPerformed

    private void atualizaConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaConsultaButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        secretariaAtualizaConsulta tela = new secretariaAtualizaConsulta(this);
        tela.setVisible(true);
    }//GEN-LAST:event_atualizaConsultaButtonActionPerformed

    private void removeConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeConsultaButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        secretariaRemoveConsulta tela = new secretariaRemoveConsulta(this);
        tela.setVisible(true);
    }//GEN-LAST:event_removeConsultaButtonActionPerformed

    private void gerarRelatorioConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarRelatorioConsultaButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        secretariaGerarRelatorioConsulta tela = new secretariaGerarRelatorioConsulta(this);
        tela.setVisible(true);
    }//GEN-LAST:event_gerarRelatorioConsultaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(secretariaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(secretariaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(secretariaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(secretariaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new secretariaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizaConsultaButton;
    private javax.swing.JButton atualizaPacienteButton;
    private javax.swing.JButton cadastrarConsultaButton;
    private javax.swing.JButton cadastrarPacienteButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton gerarRelatorioConsultaButton;
    private javax.swing.JLabel menuText;
    private javax.swing.JButton removeConsultaButton;
    private javax.swing.JButton removePacienteButton;
    // End of variables declaration//GEN-END:variables
}
