/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JFrame;

/**
 *
 * @author Gabriel
 */
public class secretariaMenu extends javax.swing.JFrame {

    private JFrame telaAnterior;
    /**
     * Creates new form secretariaMenu
     */
    public secretariaMenu(JFrame tela) {
        initComponents();
        telaAnterior = tela;
        setLocationRelativeTo(null);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/supimpa.png")).getImage());
    }

    private secretariaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuText = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        cadastrarPacienteButton = new javax.swing.JButton();
        atualizaPacienteButton = new javax.swing.JButton();
        removePacienteButton = new javax.swing.JButton();
        cadastrarConsultaButton = new javax.swing.JButton();
        atualizaConsultaButton = new javax.swing.JButton();
        removeConsultaButton = new javax.swing.JButton();
        gerarRelatorioConsultaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(446, 266));
        setResizable(false);

        menuText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuText.setText("Menu secretaria");
        menuText.setPreferredSize(new java.awt.Dimension(125, 25));

        exitButton.setText("Sair");
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });

        cadastrarPacienteButton.setText("Cadastrar Paciente");
        cadastrarPacienteButton.setMaximumSize(new java.awt.Dimension(130, 22));
        cadastrarPacienteButton.setPreferredSize(new java.awt.Dimension(130, 22));
        cadastrarPacienteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarPacienteButtonMouseClicked(evt);
            }
        });
        cadastrarPacienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPacienteButtonActionPerformed(evt);
            }
        });

        atualizaPacienteButton.setText("Atualizar Paciente");
        atualizaPacienteButton.setMaximumSize(new java.awt.Dimension(130, 22));
        atualizaPacienteButton.setPreferredSize(new java.awt.Dimension(130, 22));
        atualizaPacienteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizaPacienteButtonMouseClicked(evt);
            }
        });

        removePacienteButton.setText("Remover Paciente");
        removePacienteButton.setMaximumSize(new java.awt.Dimension(130, 22));
        removePacienteButton.setPreferredSize(new java.awt.Dimension(130, 22));
        removePacienteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removePacienteButtonMouseClicked(evt);
            }
        });

        cadastrarConsultaButton.setText("Cadastrar Consulta");
        cadastrarConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarConsultaButtonActionPerformed(evt);
            }
        });

        atualizaConsultaButton.setText("Atualizar Consulta");
        atualizaConsultaButton.setPreferredSize(new java.awt.Dimension(130, 22));
        atualizaConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaConsultaButtonActionPerformed(evt);
            }
        });

        removeConsultaButton.setText("Remover Consulta");
        removeConsultaButton.setPreferredSize(new java.awt.Dimension(130, 22));
        removeConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeConsultaButtonActionPerformed(evt);
            }
        });

        gerarRelatorioConsultaButton.setText("Gerar Relatório de Consulta");
        gerarRelatorioConsultaButton.setMaximumSize(new java.awt.Dimension(170, 22));
        gerarRelatorioConsultaButton.setPreferredSize(new java.awt.Dimension(175, 22));
        gerarRelatorioConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarRelatorioConsultaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(menuText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(cadastrarPacienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cadastrarConsultaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(atualizaPacienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(atualizaConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(removePacienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(removeConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(gerarRelatorioConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(exitButton)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(menuText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrarPacienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarConsultaButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atualizaPacienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizaConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removePacienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gerarRelatorioConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        // TODO add your handling code here:
        telaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitButtonMouseClicked

    private void cadastrarPacienteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarPacienteButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        secretariaCadastraPaciente telaCadastro = new secretariaCadastraPaciente(this);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_cadastrarPacienteButtonMouseClicked

    private void removePacienteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removePacienteButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        secretariaRemovePaciente telaRemove = new secretariaRemovePaciente(this);
        telaRemove.setVisible(true);
    }//GEN-LAST:event_removePacienteButtonMouseClicked

    private void atualizaPacienteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizaPacienteButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        secretariaAtualizaPaciente telaAtualiza = new secretariaAtualizaPaciente(this);
        telaAtualiza.setVisible(true);
    }//GEN-LAST:event_atualizaPacienteButtonMouseClicked

    private void cadastrarConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarConsultaButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        secretariaCadastraConsulta tela = new secretariaCadastraConsulta(this);
        tela.setVisible(true);
    }//GEN-LAST:event_cadastrarConsultaButtonActionPerformed

    private void atualizaConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaConsultaButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        secretariaAtualizaConsulta tela = new secretariaAtualizaConsulta(this);
        tela.setVisible(true);
    }//GEN-LAST:event_atualizaConsultaButtonActionPerformed

    private void removeConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeConsultaButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        secretariaRemoveConsulta tela = new secretariaRemoveConsulta(this);
        tela.setVisible(true);
    }//GEN-LAST:event_removeConsultaButtonActionPerformed

    private void gerarRelatorioConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarRelatorioConsultaButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        secretariaGerarRelatorioConsulta tela = new secretariaGerarRelatorioConsulta(this);
        tela.setVisible(true);
    }//GEN-LAST:event_gerarRelatorioConsultaButtonActionPerformed

    private void cadastrarPacienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPacienteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarPacienteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(secretariaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(secretariaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(secretariaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(secretariaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new secretariaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizaConsultaButton;
    private javax.swing.JButton atualizaPacienteButton;
    private javax.swing.JButton cadastrarConsultaButton;
    private javax.swing.JButton cadastrarPacienteButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton gerarRelatorioConsultaButton;
    private javax.swing.JLabel menuText;
    private javax.swing.JButton removeConsultaButton;
    private javax.swing.JButton removePacienteButton;
    // End of variables declaration//GEN-END:variables
}
